apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # any PVC name
  name: tf-pvc
spec:
  storageClassName: tf001
  accessModes:
  # ReadWriteMany(RW from multi nodes), ReadWriteOnce(RW from a node), ReadOnlyMany(R from multi nodes)
    - ReadWriteMany
  resources:
    requests:
       # storage size to use
      storage: 100Gi
